import { projects } from '@/data/projects';
import { hallCatalog, secondStoryRooms } from '@/features/immersive/catalog';
import {
  type ResolvedSiteMapRoute,
  resolveSiteMapRoutes,
  type SiteMapRoute,
} from '@/lib/site-map';

const pageFiles = Object.keys(import.meta.glob('/src/pages/**/*.astro'));

const dynamicRoutes = [
  ...projects.map((project) => ({
    href: `/projects/${project.slug}/`,
    label: project.title,
    description: project.tagline,
    category: 'projects' as const,
  })),
  ...secondStoryRooms.map((room) => ({
    href: `/rooms/${room.slug}/`,
    label: room.title,
    description: room.description,
    category: 'spaces' as const,
  })),
  ...hallCatalog.map((hall) => ({
    href: `/halls/${hall.slug}/`,
    label: hall.title,
    description: hall.description,
    category: 'spaces' as const,
  })),
] satisfies readonly SiteMapRoute[];

/**
 * Canonical inventory of every routable page generated by Astro. Static page
 * files are discovered automatically; dynamic families are expanded from the
 * same typed catalogs their getStaticPaths() implementations use.
 */
export const siteRoutes = resolveSiteMapRoutes({ pageFiles, dynamicRoutes });

/** The generated 404 file is a real output path, but not a graph destination. */
export const htmlSiteRoutes = [
  ...siteRoutes,
  {
    href: '/404.html',
    label: '404',
    description: 'Not-found page',
    category: 'experiments' as const,
  },
] satisfies readonly ResolvedSiteMapRoute[];
